M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date Tue 18 Apr 2023 09:55:42 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-18T09:55:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
%
G90
G05
T1
X126.246Y-131.818
T0
M30
